# export_kb_docs.py
# Regenerates the Knowledge Assistant corpus from the gold layer so the KA never drifts from the
# pipeline: a data dictionary (table comments, columns, sample rows, story context) plus CSV
# extracts of the gold tables, written to /Volumes/<catalog>/<schema>/<volume>/docs.

import argparse
import os
import shutil

from pyspark.sql import SparkSession

DOC_TABLES = [
    'gold_test_kpis_daily',
    'gold_bin_mix_weekly',
    'gold_param_drift_timeseries',
    'gold_throughput_daily',
    'gold_change_log',
    'gold_impact_cumulative',
    'gold_wafer_patterns',
    'gold_wafer_pattern_weekly',
    'gold_wafer_pattern_eval',
]
# Gold tables exported in full as CSV for KA retrieval
CSV_TABLES = {
    'gold_test_kpis_daily': None,
    'gold_change_log': None,
    'gold_param_drift_timeseries': None,
    'gold_impact_cumulative': None,
    'gold_wafer_pattern_weekly': None,
    # Wafer-level patterns: only systematic patterns, to keep the corpus focused
    'gold_wafer_patterns': "pattern_class NOT IN ('None', 'Random')",
}

OVERVIEW = """# KARI Semiconductor STDF Analytics Data Dictionary

## Overview
This document describes the gold-layer analytics tables for KARI Semiconductor's STDF (Standard Test Data Format) wafer sort and final test data. These tables support analysis of yield, bin distributions, parametric drift, throughput, business impact, and wafer-map spatial patterns.
It is regenerated by the STDF pipeline on every run from `{catalog}.{schema}`.

## Key Event: Austin MX-7 Yield Anomaly
- **Period**: August 18-27, 2025
- **Site**: AUS (Austin)
- **Product**: MX-7 (lots MX7-F12-W27..W29 from foundry F12 were in sort during the window)
- **Root Cause**: Probe card PC-AUS-447 Rev C installation + handler firmware HF-3.2.1 deployment on testers TST-AUS-03, TST-AUS-04, TST-AUS-05
- **Wafer-map signature**: Edge-Ring pattern on affected wafers; failing dies concentrated at the wafer edge in hard bin HB_021 (open/short contact) with elevated PT_0210 contact resistance at the edge
- **Impact**: FPY dropped ~6.8 points from baseline (~95.3% to ~88.5%), retest rate rose to 7-9%, slower probe indexing reduced UPH
- **Recovery**: Firmware rollback to HF-3.1.9 and probe card recondition on Aug 24 at 22:15, FPY normalized by Sep 1
- **Sites**: AUS (Austin), HSC (Hsinchu), PNG (Penang)
- **Products**: MX-5, MX-7, RF-22
- **Foundries**: F10, F12

## Hard Bins
- HB_001 / HB_002: pass bins
- HB_014: IDDQ / leakage failure
- HB_021: open/short (contact) failure
- HB_007: functional failure
- HB_032: parametric (Vth) failure

## Wafer-Map Pattern Classes
Every wafer is probed in one sort session, so each wafer has a complete die map. `gold_wafer_patterns` classifies each map using spatial features:
- **None**: no systematic spatial structure, normal defect level
- **Random**: no spatial structure but elevated defect density (fail rate >= 8%)
- **Center**: failures concentrated at the wafer center (CMP, implant, deposition non-uniformity)
- **Donut**: ring of failures at mid-radius (spin coat, thermal ring)
- **Edge-Ring**: failures all around the wafer edge (probe card planarity / contact, bevel etch)
- **Edge-Loc**: failures in one region of the edge (local edge damage, clamp)
- **Loc**: localized cluster in the interior (particle, reticle defect)
- **Scratch**: thin line of failures (mechanical handling)
- **Near-full**: >= 50% of dies failing (gross failure)

Features: `spatial_chi2_ratio` (dispersion of fails across 25 ring/sector cells; ~1 means spatially random), zone fail rates (center r<0.35, inner 0.35-0.65, outer 0.65-0.82, edge >=0.82 of the radius), `edge_fail_angular_conc` (0 = spread around the rim, 1 = one spot), `clustered_elongation` (principal-axis variance ratio of clustered fails; high for scratches). `reviewed_pattern` is the yield engineer's label for reviewed wafers; `gold_wafer_pattern_eval` compares it to the classifier.

## Tables
"""


def md_table(rows, cols):
    out = ['| ' + ' | '.join(cols) + ' |', '| ' + ' | '.join('---' for _ in cols) + ' |']
    for r in rows:
        out.append('| ' + ' | '.join('' if r[c] is None else str(r[c]) for c in cols) + ' |')
    return '\n'.join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--catalog', default='parijat_demos')
    parser.add_argument('--schema', default='mfg_ops')
    parser.add_argument('--volume', default='raw_data')
    args, _ = parser.parse_known_args()

    spark = SparkSession.builder.getOrCreate()
    fq = f'{args.catalog}.{args.schema}'
    docs_dir = f'/Volumes/{args.catalog}/{args.schema}/{args.volume}/docs'
    shutil.rmtree(docs_dir, ignore_errors=True)
    os.makedirs(docs_dir, exist_ok=True)

    sections = [OVERVIEW.format(catalog=args.catalog, schema=args.schema)]
    for t in DOC_TABLES:
        comment = spark.sql(f"SELECT comment FROM {args.catalog}.information_schema.tables "
                            f"WHERE table_schema = '{args.schema}' AND table_name = '{t}'").first()
        df = spark.table(f'{fq}.{t}')
        cols = [f'  - {f.name} ({f.dataType.simpleString()})' for f in df.schema.fields]
        sample = df.limit(5).collect()
        sections.append(
            f"### {t}\n**Description**: {comment[0] if comment else ''}\n\n**Columns**:\n"
            + '\n'.join(cols)
            + f"\n\n**Sample Data**:\n{md_table(sample, df.columns)}\n"
        )

    with open(f'{docs_dir}/stdf_data_dictionary.md', 'w') as f:
        f.write('\n'.join(sections))
    print(f'✓ Wrote {docs_dir}/stdf_data_dictionary.md')

    for t, where in CSV_TABLES.items():
        df = spark.table(f'{fq}.{t}')
        if where:
            df = df.where(where)
        df.toPandas().to_csv(f'{docs_dir}/{t}.csv', index=False)
        print(f'✓ Wrote {docs_dir}/{t}.csv')


if __name__ == '__main__':
    main()
